
data_name: "officeCaltech10"
num_classes: 10
cast_data: False
sample_size: 2

num_iters: 20000
gen_trade_off: 0.1
learning_rate: 0.0001
batch_size: 60
trg_trade_off: 0.01
trg_ent_src_domain_trdoff: 0.01
src_domain_trade_off: "1.0, 1.0, 1.0"








